application: testapp
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /.*
  script: manage.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest