version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - run:
          command: echo ${AWS_ACCESS_KEY_ID}

workflows:
  main:
    jobs:
      - build-and-test
      
  build-and-test:
    jobs:
      - build:
          context: test-context
